---
title: "502_HW1"
author: "Shengbo Jin"
date: "1/13/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1

```{r message=FALSE, warning=FALSE}
# Load data
library(quantmod)
load("Homework 1 Data.Rdata")
bond.data <- getSymbols("SHY", auto.assign=FALSE, from="2002-07-30",
                        to="2022-01-01")$SHY.Adjusted
bond.price.monthly <- to.monthly(bond.data, OHLC=FALSE)
head(bond.price.monthly)
```

# (a)

```{r message=FALSE}
# Get the monthly log returns, and produce a normal QQ plot
library(PerformanceAnalytics)
log.ret <- na.omit(Return.calculate(bond.price.monthly, method="log"))
qqnorm(log.ret); qqline(log.ret, lwd=4)
```

# (b)

The data is not normal. It is positively skewed to a small extent, and heavy-tailed.

# (c)

```{r}
# Plot the line of a normal QQ plot
x1 <- qnorm(0.25)
x2 <- qnorm(0.75)
y1 <- quantile(log.ret, probs=0.25)
y2 <- quantile(log.ret, probs=0.75)
b <- as.numeric((y2 - y1) / (x2 - x1))
a <- as.numeric(y1 - b * x1)
qqnorm(log.ret); qqline(log.ret, lwd=4); abline(a, b, col="green")
```

The green line matches the line in (a).

## Q2

# (a)

```{r}
# Plot a kernel density estimate of S^2, for n = 20, 100, and 500
set.seed(397)

S2_20 <- c()
for(i in 1:10000){
  x <- rnorm(20, 0, sqrt(2))
  S2_20 <- c(S2_20, var(x))
}

S2_100 <- c()
for(i in 1:10000){
  x <- rnorm(100, 0, sqrt(2))
  S2_100 <- c(S2_100, var(x))
}

S2_500 <- c()
for(i in 1:10000){
  x <- rnorm(500, 0, sqrt(2))
  S2_500 <- c(S2_500, var(x))
}

par(mfrow=c(2,2))
plot(density(S2_20), main="n = 20")
plot(density(S2_100), main="n = 100")
plot(density(S2_500), main="n = 500")
```

The distribution is positively skewed and heavy-tailed. However, as n increases, the non-normality gradually fades away, and the closeness to normality grows.

# (b)

```{r}
se_20 <- sd(S2_20)
se_100 <- sd(S2_100)
se_500 <- sd(S2_500)
print(se_20); print(se_100); print(se_500)
```

## Q3

```{r warning=FALSE}
k <- 3
C <- 1 / (3 * gamma(1 + k/3))
print(C); print(k)
```

Let k = 3 and C = 1/3, we can get an unbiased estimator of theta.
